<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_handphone</name>
   <tag></tag>
   <elementGuidId>663d422a-d4d8-4c40-8ab8-e80da173f7b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;handphone&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='handphone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>11d023a1-95f2-44ff-94dc-a8fc51226834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>882e1451-6bd3-4019-be7c-18138cfa2baf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mobile Number</value>
      <webElementGuid>cb5127cc-8301-41fc-b2a5-df0a0e00bdde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>handphone</value>
      <webElementGuid>64b47ecc-227c-436b-af9c-fed1594802db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;content&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;style_classWrapper__OCeja&quot;]/div[@class=&quot;form-wrapper&quot;]/form[1]/div[@class=&quot;form-control&quot;]/input[1]</value>
      <webElementGuid>91d0e862-4422-487b-99f1-a246e7c253b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='handphone']</value>
      <webElementGuid>06e7d4ec-552d-4b62-9feb-4e1da5a5998f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[4]/div/div[2]/form/div[3]/input</value>
      <webElementGuid>24e354bc-8516-40d1-afce-32ee2150c41b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>74454000-c690-4d72-9e08-42d8eb874762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @placeholder = 'Mobile Number' and @name = 'handphone']</value>
      <webElementGuid>c624adec-6a10-453a-bd22-76b9507ff78f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
